Picture in picture
justdvnsh/AnimeClassroom pull request #50
Opened 2021-10-06 17:37 UTC by sunny52525

Added picture in picture support, fixes #18 

https://user-images.githubusercontent.com/30768018/136255000-6cdb3b16-8d3c-4170-b1e3-1101ebe27e30.mp4

2021-10-07 16:16 UTC, justdvnsh requested changes
Hi @sunny52525 I have reviewed the changes. Please take a look. Also, please resolve the merge conflicts

2021-10-07 16:16 UTC, justdvnsh commented on app/src/main/java/divyansh/tech/animeclassroom/animeDetail/callbacks/EpisodeClickCallback.kt
> +        viewModel.startPlayerWithNewIntent(episodeUrl)
@sunny52525 Why do we need to start the activity with Intent ? can we not use jetpack navigation. Using intent here will make the coding style less consistent.

2021-10-07 16:16 UTC, justdvnsh commented on app/src/main/java/divyansh/tech/animeclassroom/common/CommonViewModel.kt
> +    }
What is this function doing ? It is first setting the value of _startPlayer to true then to false ? Why so ? And please, try to not hinder with CommonViewModel. See, if this thing can be achieved inside of the playerViewModel itself rather than CommonViewModel

2021-10-07 16:16 UTC, justdvnsh commented on app/src/main/java/divyansh/tech/animeclassroom/player/PlayerActivity.kt
> +    var episodeUrl:String?=""
Same thing. Can we not use Jetpack Navigation for this ?

2021-10-07 16:21 UTC, sunny52525 commented on app/src/main/java/divyansh/tech/animeclassroom/animeDetail/callbacks/EpisodeClickCallback.kt
> +        viewModel.startPlayerWithNewIntent(episodeUrl)
When in pip, to start a new episode and update the video we need to pass data through intent.

2021-10-07 16:23 UTC, sunny52525 commented on app/src/main/java/divyansh/tech/animeclassroom/player/PlayerActivity.kt
> +    var episodeUrl:String?=""
We need new url(to play new video and remove the old ones playing,since activity isn't destroyed args arent updated)  in onNewIntent which wasn't getting triggered with jetpack nav

2021-10-07 16:36 UTC, justdvnsh commented on app/src/main/java/divyansh/tech/animeclassroom/player/PlayerActivity.kt
> +    var episodeUrl:String?=""
Well, then we can achieve the same thing with just fragments, I think. We do not need playerActivity. We can add all the flags of player activity to main activity and then update the fragment with everytime. Now, when a new episodeUrl is passed we can handle onNewIntent Call in MainActivity itself. We can create a viewModel for mainActivity which would be an activityViewModel (i.e. it would be available for all the fragments inside mainActivity. and we can change the acitivty to lanscape through the fragment itself - using requireActivity()). Does that makes sense ? What do you think about it. This would help us not only in maintaining a consistent coding style but also, jetpack navigation makes it quite easy to test. So, it would be quite helpful if we rely on jetpack navigation only. I think that can be done.

2021-10-07 16:40 UTC, sunny52525 commented on app/src/main/java/divyansh/tech/animeclassroom/player/PlayerActivity.kt
> +    var episodeUrl:String?=""
That seem plausible, I'll do it when I get time.. most probably before tomorrows  midnight.

2021-10-07 16:53 UTC, sunny52525 commented on app/src/main/java/divyansh/tech/animeclassroom/player/PlayerActivity.kt
> +    var episodeUrl:String?=""
No actually we need a playerActivity ( its the one which goes into pip), if we make it a fragment then mainactivity will go into pip which then kills the point to clicking back to enter pip

2021-10-07 16:55 UTC, sunny52525 commented on app/src/main/java/divyansh/tech/animeclassroom/player/PlayerActivity.kt
> +    var episodeUrl:String?=""
And ideally playerActivity should receive data through intent ( docs mention to update video onNewIntent)

2021-10-07 16:57 UTC, sunny52525 commented on app/src/main/java/divyansh/tech/animeclassroom/player/PlayerActivity.kt
> +    var episodeUrl:String?=""
So we can do like other apps do like prime video or Netflix. Instead of going into pip when back pressed , go to pip when user leave app and goes to another app or homescreen

2021-10-09 08:11 UTC, justdvnsh commented on app/src/main/java/divyansh/tech/animeclassroom/player/PlayerActivity.kt
> +    var episodeUrl:String?=""
@sunny52525 Even better, let's remove the player activity all together and do it all inside a fragment. Instead of going into pip mode , lets make it a youtube like miniplayer

2021-10-10 03:23 UTC, closed without merging