offline caching in home page
justdvnsh/AnimeClassroom pull request #56
Opened 2021-10-08 09:18 UTC by krishnachaitanya0107

2021-10-09 08:10 UTC, justdvnsh requested changes
Hi @krishnachaitanya0107 . I have reviewed the files. Please make the required changes

2021-10-09 08:10 UTC, justdvnsh commented on domain/src/main/java/divyansh/tech/animeclassroom/home/HomeDefaultRepo.kt
> +const val POPULAR_ANIME="PopularAnime"
The tags are already made in an enum class. If you want to save them to the database, use enum classes ordinal. 
```
enum class HOME_TYPES(value: Int) {
    POPULAR_ANIME(1),
    RECENT_RELEASE(2)
    ....// and so on. 
}
```

Also, to use the values we can just use HOME_TYPES.POPULAR_ANIME.ordinal or something like this.

2021-10-09 08:10 UTC, justdvnsh commented on domain/src/main/java/divyansh/tech/animeclassroom/home/HomeDefaultRepo.kt
>          return flow {
Here it should be fetching the animes from the local database only first and then if there is no data in cache, then we would be making the network request.

2021-10-09 08:10 UTC, justdvnsh commented on domain/src/main/java/divyansh/tech/animeclassroom/home/HomeDefaultRepo.kt
>              val response = remoteRepo.getPopularMovies()
same

2021-10-09 08:10 UTC, justdvnsh commented on domain/src/main/java/divyansh/tech/animeclassroom/home/HomeDefaultRepo.kt
>              val response = remoteRepo.getNewSeasons()
same

2021-10-09 15:52 UTC, krishnachaitanya0107 commented
@justdvnsh  i implemented the changes , please have a look and let me know if anything can be changed  .

one thing i wish to mention - I had to move utils/Hometypes from app module to utils module because i was facing a weird 'circular dependency between the following tasks' issue  .

2021-10-10 11:50 UTC, justdvnsh commented
@krishnachaitanya0107 Hi, can you resolve the merge conflicts and also, can you please provide a working video of your feature. Thanks

2021-10-10 13:01 UTC, krishnachaitanya0107 commented
Hey , resolved the merge conflicts . About the working video , there isn't any difference that i can show in the screen recording because this feature doesn't have any ui related changes . I actually used logs to see whether data is coming from room database while testing .

2021-10-12 10:43 UTC, krishnachaitanya0107 commented
@justdvnsh , please do let me know if you want any more changes in the code . I will be happy to implement them .

2021-10-12 10:46 UTC, justdvnsh approved these changes
Looks good to me. Thank your for your contributions.

2021-10-12 10:47 UTC, merged

2021-10-12 10:55 UTC, krishnachaitanya0107 commented
Thank you @justdvnsh for going through my code , It's amazing to know that my contributions are helping out .

2021-10-12 11:05 UTC, justdvnsh commented
@krishnachaitanya0107 Offline cache has been added, but it has disrupted the flow of favorites. See the favorites tab. It will show you all the cached items. We don't want that. I am making a new issue, you can take that up if you want. The solution is pretty simple. You just need to create a separate database for the cache rather than the usual database.

2021-10-12 11:08 UTC, krishnachaitanya0107 commented
Oops , Really sorry @justdvnsh  i did not mean to mess up that flow 😅 . Ok i will take up the new issue . It would be great if you could guide me a bit on this .