Added SharedPreference
justdvnsh/AnimeClassroom pull request #71
Opened 2021-10-10 16:12 UTC by yash-k9

2021-10-12 11:00 UTC, justdvnsh requested changes
Hi @yash-k9. I have reviewed the file. Please make the required changes. Thank your for your contributions

2021-10-12 11:00 UTC, justdvnsh commented on app/src/main/java/divyansh/tech/animeclassroom/common/Constants.kt
> +
Hi @yash-k9 . We do not need to create this extra constants file. One is already present in the utils package by the name C.kt
Try to use only that file for any types of Constants.

2021-10-12 11:00 UTC, justdvnsh commented on app/src/main/java/divyansh/tech/animeclassroom/common/Constants.kt
> +
Hi @yash-k9 . We do not need to create this extra constants file. One is already present in the utils package by the name C.kt
Try to use only that file for any types of Constants.

2021-10-12 14:06 UTC, yash-k9 commented
Hi @justdvnsh, I've made the changes. please review

2021-10-13 16:34 UTC, justdvnsh approved these changes
Hi @yash-k9. Looks good to me . Thank you for your contributions

2021-10-13 16:34 UTC, merged