Added Offline Caching in the Manga Page
justdvnsh/AnimeClassroom pull request #94
Opened 2021-10-23 13:11 UTC by yash-k9

Offline Cache added to the Manga. This functions same as the offline Anime cache

2021-10-24 15:16 UTC, justdvnsh commented on domain/src/main/java/divyansh/tech/animeclassroom/Manga/MangaHomeDefaultRepo.kt
> +
HI @yash-k9 please change this function to the one written in Home page caching.

2021-10-24 15:16 UTC, justdvnsh requested changes
@yash-k9 Please make the required changes. Thank you for the contributions.

2021-10-24 17:13 UTC, yash-k9 commented on domain/src/main/java/divyansh/tech/animeclassroom/Manga/MangaHomeDefaultRepo.kt
> +
Hi @justdvnsh, should it be changed to the MangaHomeLocalRepo ?

2021-10-25 15:06 UTC, justdvnsh commented on domain/src/main/java/divyansh/tech/animeclassroom/Manga/MangaHomeDefaultRepo.kt
> +
@yash-k9 .
No, in this code, the data would be coming from the database. We need to fetch the data from the internet first, update the database and then show the database items to the user. Caching is only done, when there is no internet, then the user would not be shown an empty screen. Instead, they would still be having some data to see.

2021-10-25 18:30 UTC, yash-k9 commented on domain/src/main/java/divyansh/tech/animeclassroom/Manga/MangaHomeDefaultRepo.kt
> +
@justdvnsh, I've changed the function, the data flow would be in this order 
Fetch Remote -> Update/Store cache Data -> Emit Stored Data

2021-10-27 17:08 UTC, yash-k9 commented on domain/src/main/java/divyansh/tech/animeclassroom/Manga/MangaHomeDefaultRepo.kt
> +
Hi @justdvnsh, Are there any changes that are required

2021-10-28 16:14 UTC, justdvnsh approved these changes
Hi @yash-k9 Yeah. These were the changes. Thanks for the update and contributions.

2021-10-28 16:14 UTC, merged

2021-10-28 16:40 UTC, yash-k9 commented
Thanks @justdvnsh, can you please add the hacktoberfest-accepted label to the PR

2021-10-28 16:50 UTC, justdvnsh commented
@yash-k9 Oh, thanks for reminding. Forgot about that